BuyMed/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth.views import login, logout

app_name = 'BuyMed'
urlpatterns=[
	# re_path(r'^$', views.product_list, name='product_list'),
        re_path(r'^product/$', views.product_list, name='product_list'),
        re_path(r'^(?P<category_slug>[-\w]+)/$',
                views.product_list,
                name='product_list_by_category'),
        re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
                views.product_detail,
                name='product_detail'),
        re_path(r'^product/search/$', 
                views.product_name_search,
                name='product_name_search'),
        re_path(r'^product/search/([a-zA-Z]+)/$',
                views.product_name_search,
                name="product_name_search"),
        re_path(r'^product/login/$', login),
        re_path(r'^product/logout/$', logout),
]

BuyMedOnline/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import BuyMed


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
    path('index/', include('users.urls', namespace='users')),
    path('BuyMed/', include('BuyMed.urls', namespace='BuyMed')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path, re_path
from . import views

app_name = 'cart'
urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$',
            views.cart_add,
            name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$',
            views.cart_remove,
            name='cart_remove'),
]

users/urls.py
from django.urls import path, re_path
from . import views

app_name = 'users'
urlpatterns=[
	path('register/',views.register,name='register'),
	re_path(r'^$',views.index,name='index'),
]

templates/index.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>首页</title>
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
</head>
<body>
<div class="flex-center">
    <div class="container">
        <div>
            <h1 class="logo"><a href="#">Django Auth</a></h1>
            {% if user.is_authenticated %}
                <p>你已登录，欢迎你：<a href="#">{{ user.username }}</a></p>
                <button class="btn btn-default"><a href="{% url 'logout' %}?next={{ request.path }}">注销登录</a></button>
                <button class="btn btn-default"><a href="{% url 'password_change' %}?next={{ request.path }}">修改密码</a></button>
                <button class="btn btn-default"><a href="{% url 'BuyMed:product_list' %}">商城</a></button>
            {% else %}
                <p>你还没有登录，请
                    <button class="btn btn-default"><a href="{% url 'login' %}?next={{ request.path }}">登录</a></button>
                    或者
                    <button class="btn btn-default"><a href="{% url 'users:register' %}">注册</a></button>
                </p>
            {% endif %}
        </div>
    </div>
</div>
</body>
</html>